language: generic
sudo: required
services:
    - docker
before-install:
    - docker build -t nhukangasniemi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after-success:
    - docker build -t nhukangasniemi/multi-client ./client
    - docker build -t nhukangasniemi/nulti-nginx ./nginx
    - docker build -t nhukangasniemi/multi-server ./server
    - docker build -t nhukangasniemi/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    - docker push nhukangasniemi/multi-client
    - docker push nhukangasniemi/multi-nginx
    - docker push nhukangasniemi/multi-server
    - docker push nhukangasniemi/multi-worker
