language: generic
sudo: required
services:
    - docker:
before-install:
    - docker build -t nhukangasniemi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nhukangasniemi/react-test npm test

after-success:
    - docker build -t nhukangasniemi/multi-client ./client
    - docker build -t nhukangasniemi/multi-nginx ./nginx
    - docker build -t nhukangasniemi/multi-server ./server
    - docker build -t nhukangasniemi/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
    - docker push nhukangasniemi/multi-client
    - docker push nhukangasniemi/multi-nginx
    - docker push nhukangasniemi/multi-server
    - docker push nhukangasniemi/multi-worker

deploy:
    provider: elasticbeanstalk
    regions: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-866885367458"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
